// BudE Modular Builder v3.0.1

const fs = require("fs");
const path = require("path");

const ROOT = "docs";

const VERSION = "3.0.1-alpha";


function ensureFolder(folder){

    if(!fs.existsSync(folder)){
        fs.mkdirSync(folder,{recursive:true});
    }

}


function createFile(file,content){

    const location = path.join(ROOT,file);

    ensureFolder(path.dirname(location));


    if(!fs.existsSync(location)){

        fs.writeFileSync(location,content);

        console.log("Created:",location);

    }
    else{

        console.log("Protected:",location);

    }

}



function loadModules(){

    if(!fs.existsSync("modules.json")){

        console.log("No modules.json found");

        return [];

    }


    return JSON.parse(
        fs.readFileSync("modules.json","utf8")
    ).modules;

}



function buildCore(){


console.log("Starting BudE Builder");
console.log("Version:",VERSION);



ensureFolder(ROOT);



createFile(
"core/status.js",
`
window.BudEStatus = {

version:"${VERSION}",

online:true,

modules:[]

};
`
);



const modules = loadModules();



modules.forEach(module=>{


if(module.enabled){

console.log(
"Loading module:",
module.name
);


module.files.forEach(file=>{


createFile(
file,
`
// ${module.name}
// Generated by BudE Builder
`
);


});


BudEStatus.modules.push(module.id);


}



});



console.log("Modules installed:",modules.length);

console.log("BudE Build Complete");

}



buildCore();
