name: BudE Builder

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Run BudE Builder
        run: node seed_builder.js


      - name: Commit Generated Files
        run: |
          git config --global user.name "BudE Builder"
          git config --global user.email "bude-builder@github.com"

          git add docs

          git commit -m "BudE auto build" || echo "No changes"

          git push
